name: Convert Links

于:
  push: # 当代码推送到任何分支时触发工作流程
    分支:
      - '*' # 可以根据需要指定特定的分支，例如 'main' 或 'master'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Links
      run: |
        # 下载链接文件到工作目录中
        wget -O links.txt https://raw.githubusercontent.com/pmkol/easymosdns/rules/china_domain_list.txt
        # 检查文件是否下载成功
        if [ $? -ne 0 ]; then
          echo "Failed to download links file"
          exit 1
        fi

    - name: Convert Links
      run: |
        # 打开包含链接的文件
        cat links.txt | while read -r link; do
          # 去除链接两端的空白字符（例如换行符）
          link=$(echo "$link" | tr -d '\n\r')
          # 输出格式化后的链接
          echo "- DOMAIN,$link"
        done > china_domain_list.yaml

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add china_domain_list.yaml
        git commit -m "Convert links to DOMAIN format"
        git push

