name: Convert China Domain List

于:
  workflow_dispatch: # 手动触发工作流程
  # 或者使用定时触发
  # schedule:
  #   - cron: '0 0 * * *' # 每天UTC时间的午夜执行

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Download China Domain List
      run: |
        # 下载原链接中的文件
        wget -O china_domain_list.txt https://raw.githubusercontent.com/pmkol/easymosdns/rules/china_domain_list.txt
        # 检查文件是否下载成功
        if [ $? -ne 0 ]; then
          echo "Failed to download China Domain List file"
          exit 1
        fi

    - name: Convert and Write to YAML
      run: |
        # 打开原链接文件
        cat china_domain_list.txt | while read -r link; do
          # 去除链接两端的空白字符（例如换行符）
          link=$(echo "$link" | tr -d '\n\r')
          # 输出格式化后的链接到YAML文件
          echo "- DOMAIN,$link" >> rule/china_domain_list.yaml
        done

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rule/china_domain_list.yaml
        git commit -m "Convert China Domain List to YAML format"
        git push
